// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Button from "./Button.bs.js";
import * as Storybook from "../../../bindings/Storybook/Storybook.bs.js";

function basicUsage(param) {
  return React.createElement(Button.make, {
              label: "Button"
            });
}

var $$default = Storybook.story("Components/Button", undefined, undefined, undefined, undefined);

export {
  basicUsage ,
  $$default ,
  $$default as default,
}
/* default Not a pure module */
