// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function s(prim) {
  return prim;
}

function Index(props) {
  return React.createElement("h1", {
              className: "text-3xl font-bold underline"
            }, "Hello world!");
}

var make = Index;

export {
  s ,
  make ,
}
/* react Not a pure module */
