// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Js_undefined from "rescript/lib/es6/js_undefined.js";
import UserEvent from "@testing-library/user-event";

function click(options, init, element) {
  var options$1 = Js_undefined.fromOption(options);
  var init$1 = Js_undefined.fromOption(init);
  UserEvent.click(element, options$1, init$1);
}

function type_(options, element, text) {
  var options$1 = Js_undefined.fromOption(options);
  UserEvent.type(element, text, options$1);
}

function keyboard(options, text) {
  var options$1 = Js_undefined.fromOption(options);
  UserEvent.keyboard(text, options$1);
}

function tab(options, param) {
  var options$1 = Js_undefined.fromOption(options);
  UserEvent.tab(options$1);
}

export {
  click ,
  type_ ,
  keyboard ,
  tab ,
}
/* @testing-library/user-event Not a pure module */
