// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Js_undefined from "rescript/lib/es6/js_undefined.js";
import * as Dom from "@testing-library/dom";
import * as DomTestingLibrary__Queries from "./DomTestingLibrary_Queries/DomTestingLibrary__Queries.bs.js";

function prettyDOM(maxLength, options, element) {
  return Dom.prettyDOM(Js_undefined.fromOption(element), Js_undefined.fromOption(maxLength), Js_undefined.fromOption(options));
}

function debugScreen(param) {
  console.log(prettyDOM(undefined, undefined, undefined));
}

var makeByAltTextOptions = DomTestingLibrary__Queries.makeByAltTextOptions;

var getByAltText = DomTestingLibrary__Queries.getByAltText;

var findByAltText = DomTestingLibrary__Queries.findByAltText;

var getAllByAltText = DomTestingLibrary__Queries.getAllByAltText;

var queryAllByAltText = DomTestingLibrary__Queries.queryAllByAltText;

var findAllByAltText = DomTestingLibrary__Queries.findAllByAltText;

var makeByDisplayValueOptions = DomTestingLibrary__Queries.makeByDisplayValueOptions;

var getByDisplayValue = DomTestingLibrary__Queries.getByDisplayValue;

var findByDisplayValue = DomTestingLibrary__Queries.findByDisplayValue;

var getAllByDisplayValue = DomTestingLibrary__Queries.getAllByDisplayValue;

var queryAllByDisplayValue = DomTestingLibrary__Queries.queryAllByDisplayValue;

var findAllByDisplayValue = DomTestingLibrary__Queries.findAllByDisplayValue;

var makeByLabelTextOptions = DomTestingLibrary__Queries.makeByLabelTextOptions;

var getByLabelText = DomTestingLibrary__Queries.getByLabelText;

var findByLabelText = DomTestingLibrary__Queries.findByLabelText;

var makeByPlaceholderTextOptions = DomTestingLibrary__Queries.makeByPlaceholderTextOptions;

var getByPlaceholderText = DomTestingLibrary__Queries.getByPlaceholderText;

var findByPlaceholderText = DomTestingLibrary__Queries.findByPlaceholderText;

var getAllByPlaceholderText = DomTestingLibrary__Queries.getAllByPlaceholderText;

var queryAllByPlaceholderText = DomTestingLibrary__Queries.queryAllByPlaceholderText;

var findAllByPlaceholderText = DomTestingLibrary__Queries.findAllByPlaceholderText;

var makeByRoleOptions = DomTestingLibrary__Queries.makeByRoleOptions;

var makeByRoleOptionsWithRegex = DomTestingLibrary__Queries.makeByRoleOptionsWithRegex;

var makeByRoleOptionsWithFunction = DomTestingLibrary__Queries.makeByRoleOptionsWithFunction;

var getByRole = DomTestingLibrary__Queries.getByRole;

var findByRole = DomTestingLibrary__Queries.findByRole;

var getAllByRole = DomTestingLibrary__Queries.getAllByRole;

var queryAllByRole = DomTestingLibrary__Queries.queryAllByRole;

var findAllByRole = DomTestingLibrary__Queries.findAllByRole;

var makeByTestIdOptions = DomTestingLibrary__Queries.makeByTestIdOptions;

var getByTestId = DomTestingLibrary__Queries.getByTestId;

var findByTestId = DomTestingLibrary__Queries.findByTestId;

var getAllByTestId = DomTestingLibrary__Queries.getAllByTestId;

var queryAllByTestId = DomTestingLibrary__Queries.queryAllByTestId;

var findAllByTestId = DomTestingLibrary__Queries.findAllByTestId;

var makeByTextOptions = DomTestingLibrary__Queries.makeByTextOptions;

var getByText = DomTestingLibrary__Queries.getByText;

var findByText = DomTestingLibrary__Queries.findByText;

var getAllByText = DomTestingLibrary__Queries.getAllByText;

var queryAllByText = DomTestingLibrary__Queries.queryAllByText;

var findAllByText = DomTestingLibrary__Queries.findAllByText;

var makeByTitleOptions = DomTestingLibrary__Queries.makeByTitleOptions;

var getByTitle = DomTestingLibrary__Queries.getByTitle;

var findByTitle = DomTestingLibrary__Queries.findByTitle;

var getAllByTitle = DomTestingLibrary__Queries.getAllByTitle;

var queryAllByTitle = DomTestingLibrary__Queries.queryAllByTitle;

var findAllByTitle = DomTestingLibrary__Queries.findAllByTitle;

var UserEvent;

export {
  makeByAltTextOptions ,
  getByAltText ,
  findByAltText ,
  getAllByAltText ,
  queryAllByAltText ,
  findAllByAltText ,
  makeByDisplayValueOptions ,
  getByDisplayValue ,
  findByDisplayValue ,
  getAllByDisplayValue ,
  queryAllByDisplayValue ,
  findAllByDisplayValue ,
  makeByLabelTextOptions ,
  getByLabelText ,
  findByLabelText ,
  makeByPlaceholderTextOptions ,
  getByPlaceholderText ,
  findByPlaceholderText ,
  getAllByPlaceholderText ,
  queryAllByPlaceholderText ,
  findAllByPlaceholderText ,
  makeByRoleOptions ,
  makeByRoleOptionsWithRegex ,
  makeByRoleOptionsWithFunction ,
  getByRole ,
  findByRole ,
  getAllByRole ,
  queryAllByRole ,
  findAllByRole ,
  makeByTestIdOptions ,
  getByTestId ,
  findByTestId ,
  getAllByTestId ,
  queryAllByTestId ,
  findAllByTestId ,
  makeByTextOptions ,
  getByText ,
  findByText ,
  getAllByText ,
  queryAllByText ,
  findAllByText ,
  makeByTitleOptions ,
  getByTitle ,
  findByTitle ,
  getAllByTitle ,
  queryAllByTitle ,
  findAllByTitle ,
  UserEvent ,
  prettyDOM ,
  debugScreen ,
}
/* @testing-library/dom Not a pure module */
