// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function make(props) {
  return React.createElement(props.Component, props.pageProps);
}

export {
  make ,
}
/* react Not a pure module */
