// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as $$Document from "next/document";

function _Document$default(props) {
  return React.createElement($$Document.Html, {
              className: "dark",
              children: null
            }, React.createElement($$Document.Head, {}), React.createElement("body", undefined, React.createElement($$Document.Main, {}), React.createElement($$Document.NextScript, {})));
}

var $$default = _Document$default;

export {
  $$default ,
  $$default as default,
}
/* react Not a pure module */
