// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Navbar from "./Navbar.bs.js";
import * as Storybook from "../../../bindings/Storybook/Storybook.bs.js";

function basicUsage(param) {
  return React.createElement(Navbar.make, {});
}

var $$default = Storybook.story("Components/Navbar", undefined, undefined, undefined, undefined);

export {
  basicUsage ,
  $$default ,
  $$default as default,
}
/* default Not a pure module */
