// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function Navbar(props) {
  return React.createElement("nav", undefined, "this is my nav");
}

var make = Navbar;

export {
  make ,
}
/* react Not a pure module */
