// Generated by ReScript, PLEASE EDIT WITH CARE


var Req = {};

var Res = {};

var GetServerSideProps = {
  Req: Req,
  Res: Res
};

var GetStaticProps = {};

var GetStaticPaths = {};

var Link = {};

var Events = {};

var Router = {
  Events: Events
};

var $$Error = {};

var Dynamic = {};

var $$Image;

var Seo;

var $$Document;

export {
  $$Image ,
  Seo ,
  $$Document ,
  GetServerSideProps ,
  GetStaticProps ,
  GetStaticPaths ,
  Link ,
  Router ,
  $$Error ,
  Dynamic ,
}
/* No side effect */
