// Generated by ReScript, PLEASE EDIT WITH CARE


var Req = {};

var Res = {};

var GetServerSideProps = {
  Req: Req,
  Res: Res
};

var GetStaticProps = {};

var GetStaticPaths = {};

var Link = {};

var Events = {};

var Router = {
  Events: Events
};

var Html = {};

var Head = {};

var Main = {};

var NextScript = {};

var $$Document = {
  Html: Html,
  Head: Head,
  Main: Main,
  NextScript: NextScript
};

var $$Error = {};

var Dynamic = {};

export {
  GetServerSideProps ,
  GetStaticProps ,
  GetStaticPaths ,
  Link ,
  Router ,
  $$Document ,
  $$Error ,
  Dynamic ,
}
/* No side effect */
