// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Cypress from "../../../bindings/Cypress/Cypress.bs.js";

Cypress.describe("Root path", (function (param) {
        Cypress.it("/", (function (param) {
                cy.visit("/", undefined);
                cy.contains(undefined, "EXAMPLE 1", undefined);
              }));
      }));

export {
  
}
/*  Not a pure module */
