// Generated by ReScript, PLEASE EDIT WITH CARE

import * as DomTestingLibrary__Queries__ByRole from "./DomTestingLibrary__Queries__ByRole.bs.js";
import * as DomTestingLibrary__Queries__ByText from "./DomTestingLibrary__Queries__ByText.bs.js";
import * as DomTestingLibrary__Queries__ByTitle from "./DomTestingLibrary__Queries__ByTitle.bs.js";
import * as DomTestingLibrary__Queries__ByTestId from "./DomTestingLibrary__Queries__ByTestId.bs.js";
import * as DomTestingLibrary__Queries__ByAltText from "./DomTestingLibrary__Queries__ByAltText.bs.js";
import * as DomTestingLibrary__Queries__ByLabelText from "./DomTestingLibrary__Queries__ByLabelText.bs.js";
import * as DomTestingLibrary__Queries__ByDisplayValue from "./DomTestingLibrary__Queries__ByDisplayValue.bs.js";
import * as DomTestingLibrary__Queries__ByPlaceholderText from "./DomTestingLibrary__Queries__ByPlaceholderText.bs.js";

var makeByAltTextOptions = DomTestingLibrary__Queries__ByAltText.makeByAltTextOptions;

var getByAltText = DomTestingLibrary__Queries__ByAltText.getByAltText;

var findByAltText = DomTestingLibrary__Queries__ByAltText.findByAltText;

var getAllByAltText = DomTestingLibrary__Queries__ByAltText.getAllByAltText;

var queryAllByAltText = DomTestingLibrary__Queries__ByAltText.queryAllByAltText;

var findAllByAltText = DomTestingLibrary__Queries__ByAltText.findAllByAltText;

var makeByDisplayValueOptions = DomTestingLibrary__Queries__ByDisplayValue.makeByDisplayValueOptions;

var getByDisplayValue = DomTestingLibrary__Queries__ByDisplayValue.getByDisplayValue;

var findByDisplayValue = DomTestingLibrary__Queries__ByDisplayValue.findByDisplayValue;

var getAllByDisplayValue = DomTestingLibrary__Queries__ByDisplayValue.getAllByDisplayValue;

var queryAllByDisplayValue = DomTestingLibrary__Queries__ByDisplayValue.queryAllByDisplayValue;

var findAllByDisplayValue = DomTestingLibrary__Queries__ByDisplayValue.findAllByDisplayValue;

var makeByLabelTextOptions = DomTestingLibrary__Queries__ByLabelText.makeByLabelTextOptions;

var getByLabelText = DomTestingLibrary__Queries__ByLabelText.getByLabelText;

var findByLabelText = DomTestingLibrary__Queries__ByLabelText.findByLabelText;

var makeByPlaceholderTextOptions = DomTestingLibrary__Queries__ByPlaceholderText.makeByPlaceholderTextOptions;

var getByPlaceholderText = DomTestingLibrary__Queries__ByPlaceholderText.getByPlaceholderText;

var findByPlaceholderText = DomTestingLibrary__Queries__ByPlaceholderText.findByPlaceholderText;

var getAllByPlaceholderText = DomTestingLibrary__Queries__ByPlaceholderText.getAllByPlaceholderText;

var queryAllByPlaceholderText = DomTestingLibrary__Queries__ByPlaceholderText.queryAllByPlaceholderText;

var findAllByPlaceholderText = DomTestingLibrary__Queries__ByPlaceholderText.findAllByPlaceholderText;

var makeByRoleOptions = DomTestingLibrary__Queries__ByRole.makeByRoleOptions;

var makeByRoleOptionsWithRegex = DomTestingLibrary__Queries__ByRole.makeByRoleOptionsWithRegex;

var makeByRoleOptionsWithFunction = DomTestingLibrary__Queries__ByRole.makeByRoleOptionsWithFunction;

var getByRole = DomTestingLibrary__Queries__ByRole.getByRole;

var findByRole = DomTestingLibrary__Queries__ByRole.findByRole;

var getAllByRole = DomTestingLibrary__Queries__ByRole.getAllByRole;

var queryAllByRole = DomTestingLibrary__Queries__ByRole.queryAllByRole;

var findAllByRole = DomTestingLibrary__Queries__ByRole.findAllByRole;

var makeByTestIdOptions = DomTestingLibrary__Queries__ByTestId.makeByTestIdOptions;

var getByTestId = DomTestingLibrary__Queries__ByTestId.getByTestId;

var findByTestId = DomTestingLibrary__Queries__ByTestId.findByTestId;

var getAllByTestId = DomTestingLibrary__Queries__ByTestId.getAllByTestId;

var queryAllByTestId = DomTestingLibrary__Queries__ByTestId.queryAllByTestId;

var findAllByTestId = DomTestingLibrary__Queries__ByTestId.findAllByTestId;

var makeByTextOptions = DomTestingLibrary__Queries__ByText.makeByTextOptions;

var getByText = DomTestingLibrary__Queries__ByText.getByText;

var findByText = DomTestingLibrary__Queries__ByText.findByText;

var getAllByText = DomTestingLibrary__Queries__ByText.getAllByText;

var queryAllByText = DomTestingLibrary__Queries__ByText.queryAllByText;

var findAllByText = DomTestingLibrary__Queries__ByText.findAllByText;

var makeByTitleOptions = DomTestingLibrary__Queries__ByTitle.makeByTitleOptions;

var getByTitle = DomTestingLibrary__Queries__ByTitle.getByTitle;

var findByTitle = DomTestingLibrary__Queries__ByTitle.findByTitle;

var getAllByTitle = DomTestingLibrary__Queries__ByTitle.getAllByTitle;

var queryAllByTitle = DomTestingLibrary__Queries__ByTitle.queryAllByTitle;

var findAllByTitle = DomTestingLibrary__Queries__ByTitle.findAllByTitle;

export {
  makeByAltTextOptions ,
  getByAltText ,
  findByAltText ,
  getAllByAltText ,
  queryAllByAltText ,
  findAllByAltText ,
  makeByDisplayValueOptions ,
  getByDisplayValue ,
  findByDisplayValue ,
  getAllByDisplayValue ,
  queryAllByDisplayValue ,
  findAllByDisplayValue ,
  makeByLabelTextOptions ,
  getByLabelText ,
  findByLabelText ,
  makeByPlaceholderTextOptions ,
  getByPlaceholderText ,
  findByPlaceholderText ,
  getAllByPlaceholderText ,
  queryAllByPlaceholderText ,
  findAllByPlaceholderText ,
  makeByRoleOptions ,
  makeByRoleOptionsWithRegex ,
  makeByRoleOptionsWithFunction ,
  getByRole ,
  findByRole ,
  getAllByRole ,
  queryAllByRole ,
  findAllByRole ,
  makeByTestIdOptions ,
  getByTestId ,
  findByTestId ,
  getAllByTestId ,
  queryAllByTestId ,
  findAllByTestId ,
  makeByTextOptions ,
  getByText ,
  findByText ,
  getAllByText ,
  queryAllByText ,
  findAllByText ,
  makeByTitleOptions ,
  getByTitle ,
  findByTitle ,
  getAllByTitle ,
  queryAllByTitle ,
  findAllByTitle ,
}
/* DomTestingLibrary__Queries__ByRole Not a pure module */
