// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Js_undefined from "rescript/lib/es6/js_undefined.js";
import * as Dom from "@testing-library/dom";

function makeByTestIdOptions(exact, normalizer, param) {
  return {
          exact: Js_undefined.fromOption(exact),
          normalizer: Js_undefined.fromOption(normalizer)
        };
}

function getByTestId(options, matcher, element) {
  return Dom.getByTestId(element, matcher.VAL, options);
}

function findByTestId(options, matcher, element) {
  return Dom.findByTestId(element, matcher.VAL, options);
}

function getAllByTestId(options, matcher, element) {
  return Dom.getAllByTestId(element, matcher.VAL, options);
}

function queryAllByTestId(options, matcher, element) {
  return Dom.queryAllByTestId(element, matcher.VAL, options);
}

function findAllByTestId(options, matcher, element) {
  return Dom.findAllByTestId(element, matcher.VAL, options);
}

export {
  makeByTestIdOptions ,
  getByTestId ,
  findByTestId ,
  getAllByTestId ,
  queryAllByTestId ,
  findAllByTestId ,
}
/* @testing-library/dom Not a pure module */
