// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Js_undefined from "rescript/lib/es6/js_undefined.js";
import * as Dom from "@testing-library/dom";

function makeByTextOptions(selector, exact, ignore, normalizer, param) {
  return {
          selector: Js_undefined.fromOption(selector),
          exact: Js_undefined.fromOption(exact),
          ignore: Js_undefined.fromOption(ignore),
          normalizer: Js_undefined.fromOption(normalizer)
        };
}

function getByText(options, element, matcher) {
  return Dom.getByText(element, matcher.VAL, options);
}

function findByText(options, matcher, element) {
  return Dom.findByText(element, matcher.VAL, options);
}

function getAllByText(options, matcher, element) {
  return Dom.getAllByText(element, matcher.VAL, options);
}

function queryAllByText(options, matcher, element) {
  return Dom.queryAllByText(element, matcher.VAL, options);
}

function findAllByText(options, matcher, element) {
  return Dom.findAllByText(element, matcher.VAL, options);
}

export {
  makeByTextOptions ,
  getByText ,
  findByText ,
  getAllByText ,
  queryAllByText ,
  findAllByText ,
}
/* @testing-library/dom Not a pure module */
