// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Js_undefined from "rescript/lib/es6/js_undefined.js";
import * as Dom from "@testing-library/dom";

function makeByDisplayValueOptions(exact, normalizer, param) {
  return {
          exact: Js_undefined.fromOption(exact),
          normalizer: Js_undefined.fromOption(normalizer)
        };
}

function getByDisplayValue(options, matcher, element) {
  return Dom.getByDisplayValue(element, matcher.VAL, options);
}

function findByDisplayValue(options, matcher, element) {
  return Dom.findByDisplayValue(element, matcher.VAL, options);
}

function getAllByDisplayValue(options, matcher, element) {
  return Dom.getAllByDisplayValue(element, matcher.VAL, options);
}

function queryAllByDisplayValue(options, matcher, element) {
  return Dom.queryAllByDisplayValue(element, matcher.VAL, options);
}

function findAllByDisplayValue(options, matcher, element) {
  return Dom.findAllByDisplayValue(element, matcher.VAL, options);
}

export {
  makeByDisplayValueOptions ,
  getByDisplayValue ,
  findByDisplayValue ,
  getAllByDisplayValue ,
  queryAllByDisplayValue ,
  findAllByDisplayValue ,
}
/* @testing-library/dom Not a pure module */
