// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Js_undefined from "rescript/lib/es6/js_undefined.js";
import * as Dom from "@testing-library/dom";

function makeByTitleOptions(exact, normalizer, param) {
  return {
          exact: Js_undefined.fromOption(exact),
          normalizer: Js_undefined.fromOption(normalizer)
        };
}

function getByTitle(options, matcher, element) {
  return Dom.getByTitle(element, matcher.VAL, options);
}

function findByTitle(options, matcher, element) {
  return Dom.findByTitle(element, matcher.VAL, options);
}

function getAllByTitle(options, matcher, element) {
  return Dom.getAllByTitle(element, matcher.VAL, options);
}

function queryAllByTitle(options, matcher, element) {
  return Dom.queryAllByTitle(element, matcher.VAL, options);
}

function findAllByTitle(options, matcher, element) {
  return Dom.findAllByTitle(element, matcher.VAL, options);
}

export {
  makeByTitleOptions ,
  getByTitle ,
  findByTitle ,
  getAllByTitle ,
  queryAllByTitle ,
  findAllByTitle ,
}
/* @testing-library/dom Not a pure module */
