// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Button from "../../Components/Button/Button.bs.js";
import * as Vitest from "rescript-vitest/src/Vitest.bs.js";
import * as Vitest$1 from "vitest";
import * as ReactTestingLibrary from "rescript-react-testing-library/src/ReactTestingLibrary.bs.js";

Vitest.describe("Button", undefined, (function (param) {
        Vitest$1.beforeEach(function () {
              return ReactTestingLibrary.renderOnScreen(React.createElement(Button.make, {
                              label: "Button"
                            }));
            });
        Vitest.test("render Red option", undefined, (function (param) {
                Vitest$1.expect(ReactTestingLibrary.getByRole(ReactTestingLibrary.makeByRoleOptions(undefined, undefined, "Red", undefined), {
                            NAME: "Str",
                            VAL: "option"
                          }, document)).toMatchSnapshot();
              }));
        Vitest.test("render Green option", undefined, (function (param) {
                Vitest$1.expect(ReactTestingLibrary.getByRole(ReactTestingLibrary.makeByRoleOptions(undefined, undefined, "Green", undefined), {
                            NAME: "Str",
                            VAL: "option"
                          }, document)).toMatchSnapshot();
              }));
        Vitest.test("render Blue option", undefined, (function (param) {
                Vitest$1.expect(ReactTestingLibrary.getByRole(ReactTestingLibrary.makeByRoleOptions(undefined, undefined, "Blue", undefined), {
                            NAME: "Str",
                            VAL: "option"
                          }, document)).toMatchSnapshot();
              }));
      }));

export {
  
}
/*  Not a pure module */
