// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Vitest from "rescript-vitest/src/Vitest.bs.js";
import * as Vitest$1 from "vitest";

Vitest.describe("Hello, Vitest", undefined, (function (param) {
        Vitest.test("This is a test case", undefined, (function (param) {
                Vitest$1.expect(3).toBe(3);
                Vitest$1.expect([
                        1,
                        2,
                        3
                      ]).toContain(2);
                Vitest$1.expect("Hello, ReScript-Vitest!").toContain("ReScript");
              }));
      }));

export {
  
}
/*  Not a pure module */
